### ISSUE TITLE
Warning: TF_OLD_DATA ignoring data from the past for....

### ISSUE THREAD

**Issue by WQ-2001-mc** [robotics-upo/cloud_concatenator#1]
![image](https://user-images.githubusercontent.com/102968155/216271788-efc00358-51ca-4acc-a848-ac47e976a303.png)

**Comment by david-alejo** [comment]
Dear 748811693aB (are you human?) :)

This error is an internal ROS error that's usually found in simulation or when reproducing ROSBAGs.

For example, when dealing with ROSBAG you have to make sure:

1. The global parameter "use_sim_time" is set to true:   > rosparam set use_sim_time true
2.  You make the rosbag util publish the recorded clock:  > rosbag play <your bag file> --clock

(if you use a gazebo simulation, you only have to run the first point)

Hope it helps. 

Best,

**Comment by WQ-2001-mc** [comment]
Of course, I am a humanbeing. just with a weired user name. LOL    :->
your method helps me a lot . Thank you very much.
